[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
fs_permissions = [{ access = "read", path = "./testdata"}]

[dependencies]
"@openzeppelin-contracts" = "5.0.1"
forge-std = "1.9.2"
risc0-ethereum = { version = "1.0.0", url = "https://github.com/vlayer-xyz/risc0-ethereum/releases/download/v1.0.0-soldeer-no-remappings/contracts.zip" }
vlayer = { version = "0.1.0-nightly-20241115-70dfc11" }
eigenlayer-middleware = { version = "1.0.0", git = "git@github.com:Layr-Labs/eigenlayer-middleware.git", rev = "7d49b5181b09198ed275783453aa082bb3766990" }
eas = { version = "1.0.0", git = "git@github.com:ethereum-attestation-service/eas-contracts.git", rev = "558250dae4cb434859b1ac3b6d32833c6448be21" }

[soldeer]
# whether soldeer manages remappings
remappings_generate = false
# whether soldeer re-generates all remappings when installing, updating or uninstalling deps
remappings_regenerate = false

